db:
  username: ${username.value:postgres}
  password: passііі
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 12
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 2
      timeout: 2

  #spring.profiles.active=qa


logging:
  level:
    root: INFO
    com.foretruff.spring.database.pool: info
    org.springframework.jdbc.core: TRACE
  file:
    name: foretruff.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:auto: update
      default_schema: public
    open-in-view: false
  gson:
    date-format:

springdoc:
  swagger-ui:
    oauth:
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

